# Generated by Django 6.1.1 on 2026-09-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='날짜')),
                ('total', models.IntegerField(default=0, verbose_name='총 신고건수')),
                ('pending', models.IntegerField(default=0, verbose_name='처리 대기')),
                ('approved', models.IntegerField(default=0, verbose_name='승인')),
                ('rejected', models.IntegerField(default=0, verbose_name='반려')),
            ],
        ),
    ]
